# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IoDgOLVSqlCtC7YCAzgZe9szBxGdB2kq
"""

pip install fastapi uvicorn sqlalchemy pydantic

from typing import List, Optional
from fastapi import FastAPI, HTTPException, Depends, status
from pydantic import BaseModel, Field
from sqlalchemy import create_engine, Column, Integer, String, Float, Boolean
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# ==========================================
# 1. DATABASE CONFIGURATION (SQLite)
# ==========================================
DATABASE_URL = "sqlite:///./inventory.db"

# connect_args={"check_same_thread": False} is required only for SQLite
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# SQLAlchemy Database Model
class ProductDB(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    description = Column(String, nullable=True)
    price = Column(Float, nullable=False)
    in_stock = Column(Boolean, default=True)


# Create tables in the database
Base.metadata.create_all(bind=engine)


# Dependency to get DB session per request
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ==========================================
# 2. PYDANTIC SCHEMAS (Data Validation)
# ==========================================
class ProductCreate(BaseModel):
    """Schema for creating a product."""
    name: str = Field(..., min_length=1, max_length=100, example="Wireless Mouse")
    description: Optional[str] = Field(None, example="Ergonomic optical mouse")
    price: float = Field(..., gt=0, example=29.99)
    in_stock: bool = True


class ProductUpdate(BaseModel):
    """Schema for updating a product (all fields optional)."""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    description: Optional[str] = None
    price: Optional[float] = Field(None, gt=0)
    in_stock: Optional[bool] = None


class ProductResponse(BaseModel):
    """Schema for returning product data."""
    id: int
    name: str
    description: Optional[str]
    price: float
    in_stock: bool

    class Config:
        from_attributes = True  # Allows Pydantic to read ORM objects


# ==========================================
# 3. FASTAPI APP & CRUD ENDPOINTS
# ==========================================
app = FastAPI(
    title="Product Inventory CRUD API",
    description="A complete CRUD REST API built with FastAPI and SQLite",
    version="1.0.0"
)


# --- CREATE (POST) ---
@app.post(
    "/products/",
    response_model=ProductResponse,
    status_code=status.HTTP_201_CREATED,
    tags=["Products"]
)
def create_product(product: ProductCreate, db: Session = Depends(get_db)):
    """Create a new product in the database."""
    db_product = ProductDB(**product.model_dump())
    db.add(db_product)
    db.commit()
    db.refresh(db_product)
    return db_product


# --- READ ALL (GET) ---
@app.get(
    "/products/",
    response_model=List[ProductResponse],
    tags=["Products"]
)
def read_products(skip: int = 0, limit: int = 10, db: Session = Depends(get_db)):
    """Retrieve all products with pagination."""
    products = db.query(ProductDB).offset(skip).limit(limit).all()
    return products


# --- READ ONE (GET) ---
@app.get(
    "/products/{product_id}",
    response_model=ProductResponse,
    tags=["Products"]
)
def read_product(product_id: int, db: Session = Depends(get_db)):
    """Retrieve a single product by its ID."""
    db_product = db.query(ProductDB).filter(ProductDB.id == product_id).first()
    if not db_product:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Product with ID {product_id} not found."
        )
    return db_product


# --- UPDATE (PUT) ---
@app.put(
    "/products/{product_id}",
    response_model=ProductResponse,
    tags=["Products"]
)
def update_product(product_id: int, product_update: ProductUpdate, db: Session = Depends(get_db)):
    """Update an existing product's fields."""
    db_product = db.query(ProductDB).filter(ProductDB.id == product_id).first()
    if not db_product:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Product with ID {product_id} not found."
        )

    # Update only fields that were passed in the request
    update_data = product_update.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_product, key, value)

    db.commit()
    db.refresh(db_product)
    return db_product


# --- DELETE (DELETE) ---
@app.delete(
    "/products/{product_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    tags=["Products"]
)
def delete_product(product_id: int, db: Session = Depends(get_db)):
    """Delete a product from the database."""
    db_product = db.query(ProductDB).filter(ProductDB.id == product_id).first()
    if not db_product:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Product with ID {product_id} not found."
        )

    db.delete(db_product)
    db.commit()
    return None